### ISSUE TITLE
iSH Fails to update /etc/resolv.conf on Network change

### ISSUE THREAD

**Issue by jaclu** [ish-app/ish.app#34]
I have had exchanges with some of the devs over this. At first their utter failure to even agree this was an issue surprised me. Eventually I realized that if they are in permissive regions, where 3rd party nameservers are tolerated by ISPs, they would never notice this.

They change network, and their now obsolete nameservers list can still be used - for them the supposed issue does not exist.

However this is not always the case, and where 3rd party nameservers are not accepted by the ISPs a network change instantly causes iSH to loose connectivity. You can still communicate by IP#, but that is kind of irrelevant. If you loose lookups, you essentially got disconnected.

**Comment by jaclu** [comment]
To test for this issue:
- Start iSH
- Change network connection
- Compare iOS nameservers to what is in iSH /etc/resolv.conf

If they differ you are suffering this bug. Due to permissive routing you might not be negatively impacted, but it is there.

**Comment by Mnpn** [comment]
Hi, did you mean to post this issue on the website's repository?

**Comment by jaclu** [comment]
No i meant to post it as an bug/issue here, since when I post on the discord forum it tends to just scroll of screen

**Comment by jaclu** [comment]
or am i using the wrong git?

**Comment by jaclu** [comment]
indeed i was, oops will remove it
